### ISSUE TITLE
'malloc.h' file not found

### ISSUE THREAD

**Issue by olexandr-konovalov** [lbfm-rwth/carat#2]
On macOS, I have the following:

```
$ make
cd functions/Autgrp; make CC="gcc" CFLAGS="-g -Wall -DDIAG1" TOPDIR=/Users/alexk/GITREPS/carat
gcc -g -Wall -DDIAG1 -c -DTOPDIR=\"/Users/alexk/GITREPS/carat\" -DTABLES=\"/Users/alexk/GITREPS/carat/tables/\" -DATOMS=\"/Users/alexk/GITREPS/carat/tables/atoms/\" -DTABLEDIM=\"/Users/alexk/GITREPS/carat/tables/dim\" -I/Users/alexk/GITREPS/carat/include autgrp.c -o autgrp.o
In file included from autgrp.c:3:
/Users/alexk/GITREPS/carat/include/typedef.h:13:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[1]: *** [autgrp.o] Error 1
make: *** [Autgrp] Error 2
```

the workaround is to remove the line `#include <malloc.h>` from `include/typedef.h` (I have figured this out because this is what carat GAP package is doing), but a proper solution should be found.

**Comment by fingolfin** [comment]
This *is* the proper solution. Use of malloc.h is incorrect, the correct header to get malloc.h (well, at least since the late 80ies... ;-) is to include string.h

**Comment by gaehler** [comment]
My Linux man page says stdlib.h. Not malloc.h in any case, that is low level and not intended for direct inclusion.

**Comment by fingolfin** [comment]
Yes, `stdlib.h` is right -- that was a braino on my part, sorry for the confusion.

And malloc.h is not part of any standard, and not available on many systems; it was never correct to include it (except parts pre ANSI-C on some weird machines, but even then I doubt it -- so far all code that I found which includes it did so because the author copy & pasted it, mistakenly thinking that this was need for malloc.
