### ISSUE TITLE
Make Carat binaries relocatable

### ISSUE THREAD

**Issue by gaehler** [lbfm-rwth/carat#21]
One of the more annoying aspects of Carat is, that the location of its data tables is compiled into the binaries. This location has to be decided at compile time, which makes it difficult to redistribute binaries. Moreover, the location of the data tables is communicated to each and every file by preprocessor defines on the command line, even though only a minority of files actually need them. In fact, even four related defines for `TOPDIR`, `TABLES`, `TABLEDIM`, and `ATOMS`, are communicated to each file, which contributes to the excessive length of the compilation log.

I propose therefore to do the following:

1. As files in only 4 of the 24 directories in `functions` actually need any of the above mentioned defines, one could remove them completely from the Makefiles in the other 20 directories. This is little work, easy to do, and has a big effect on the size of the compilation log. I can prepare such a PR.
2. Write a function such as this one:
 ```
void get_data_dir(char *result, const char *str) {
   sprintf(result, "%s/%s", TOPDIR, str);
}
```
3. Use this function wherever data tables are needed, so that the above defines can be removed altogether (except for the function and the Makefiles).
4. Having achieved that, it is then easy to enhance the function to look for alternative locations of the data tables, e.g. by reading a directory from an environment variable, or from an entry in a configuration file, etc. I do no know yet what is most convenient and most portable.

**Comment by gaehler** [comment]
@DominikBernhardt Any opinions on this proposal? Part 1 is already merged, and I can do the rest as well, if there are no objections (once PR #26 is merged). I'm only hesitant on there to put such a function (which directory, which file, its own file?). I think it would be really useful to have the option of configuring the data location at run time.

**Comment by DominikBernhardt** [comment]
I guess we could make a directory for maintenance functions? Is that something one usually does?
Or just a file containing the functions we need. 

Apart from that I don't have any objections.

**Comment by fingolfin** [comment]
I believe @gaehler already implemented all of what was described here so far. And in the meantime, I slightly refactored that code.

But right now, the compile location of carat still is hardcoded, which isn't great. Nor is passing an env variable the best way to go about this, IMHO. I suggest the following instead, with search locations ordered by priority

1. Every tool should have an option to specify an alternate data dir path, to override whatever else the binary might use otherwise.
2. If not given, look for the `CARAT_DIR` environment variable, and use that.
3. Next, determine the location of the currently ruing executable; then, search for the data path relative to this location. I.e, search in `EXECUTABLE_PATH/../tables/`, provided such a directory exists.
4. To eventually support `make install`, where I suspect the binaries would go into `PREFIX/bin` but the data would go into `PREFIX/share/carat/tables`, we could next search in `EXECUTABLE_PATH/../share/carat/tables`.
5. As final fallback and as a variant to 3, hardcode `PREFIX/share/carat/tables/` in the binary as a last resort fallback

What we should *not* do anymore is hardcode the path of the directory in which carat was compiled. This goes against best practices; it also makes it harder to support `make install` properly, as it would force us to recompile and relink stuff for installation. Even if in the end many people might run `carat` from the place they compiled it in, I think the above steps 1-5 sufficiently cover this, based on experience with GAP.

I will work on making a PR for this, which can be refined based on your feedback.

**Comment by gaehler** [comment]
When I implemented get_data_dir(), the goal was to locate the data tables with a single piece of code in one place, in order to be able to change or augment that code with further methods. The actual methods I implemented were not meant to be the final answer. I thought of trying a location relative to the location of the running binary, but a search on the net indicated that this was difficult to implement in a portable way. That's why I came up with the environment variable CARAT_DIR. But if another method works for GAP, ot should be good enough here, too. As there are so many CARAT executables, I refrained from equipping them all with an option specifying the data directory. But of course, one could do that (including the necessary documentation changes). So, I certainly agree with the overall strategy sketched above.
